# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-04 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('fee', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
